template:
  name: go
  env:
    LD_RELEASE_GO_IMPORT_PATH: github.com/launchdarkly/go-ntlm-proxy-auth

publications:
  - url: https://godoc.org/github.com/launchdarkly/go-ntlm-proxy-auth
    description: documentation
